import { useState } from "react";

const RISK_STYLES = {
  Low: { className: "risk-low", label: "Low Risk" },
  Suspicious: { className: "risk-suspicious", label: "Suspicious" },
  High: { className: "risk-high", label: "High Risk" },
};

const SCREENSHOT_ACTION_PATTERN = /upload (the )?screenshot|paste the (text|screenshot)/i;

function requestScreenshotUpload() {
  window.dispatchEvent(new Event("request-screenshot-upload"));
}

export default function RiskResult({ result }) {
  const [language, setLanguage] = useState("en");
  const riskStyle = RISK_STYLES[result.riskLevel] || RISK_STYLES.Suspicious;
  const score = Math.max(0, Math.min(100, Number(result.riskScore) || 0));

  return (
    <div className={`risk-result card ${riskStyle.className}`}>
      <div className="risk-header">
        <span className="risk-badge">{riskStyle.label}</span>
        <div className="risk-gauge">
          <div className="risk-gauge-value">
            {score}
            <small>/100</small>
          </div>
          <div className="risk-gauge-label">Risk score</div>
        </div>
      </div>

      <div
        className="risk-meter"
        role="meter"
        aria-valuenow={score}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label="Risk score"
      >
        <div className="risk-meter-fill" style={{ width: `${score}%` }} />
      </div>
      <div className="risk-scale">
        <span>Safe</span>
        <span>Suspicious</span>
        <span>Dangerous</span>
      </div>

      <p className="risk-summary">{result.summary}</p>

      {result.evidence?.length > 0 && (
        <section className="evidence-section">
          <h3>Evidence behind this assessment</h3>
          <ul className="evidence-list">
            {result.evidence.map((item, idx) => (
              <li key={idx} className="evidence-item">
                {item.pattern && <span className="evidence-pattern">{item.pattern}</span>}
                <blockquote className="evidence-snippet">“{item.snippet}”</blockquote>
                <p className="evidence-reason">{item.reason}</p>
              </li>
            ))}
          </ul>
        </section>
      )}

      {result.recommendedActions?.length > 0 && (
        <section className="actions-section">
          <h3>Recommended next actions</h3>
          <ul className="actions-list">
            {result.recommendedActions.map((action, idx) =>
              SCREENSHOT_ACTION_PATTERN.test(action) ? (
                <li key={idx} className="action-item-with-cta">
                  <span>{action}</span>
                  <button type="button" className="btn-secondary action-cta" onClick={requestScreenshotUpload}>
                    Upload screenshot
                  </button>
                </li>
              ) : (
                <li key={idx}>{action}</li>
              )
            )}
          </ul>
        </section>
      )}

      <section className="guidance-section">
        <div className="guidance-header">
          <h3>Safety guidance</h3>
          <div className="language-toggle" role="group" aria-label="Guidance language">
            <button
              type="button"
              className={language === "en" ? "active" : ""}
              aria-pressed={language === "en"}
              onClick={() => setLanguage("en")}
            >
              English
            </button>
            <button
              type="button"
              className={language === "hi" ? "active" : ""}
              aria-pressed={language === "hi"}
              onClick={() => setLanguage("hi")}
            >
              हिन्दी
            </button>
          </div>
        </div>
        <p className="guidance-text" lang={language === "en" ? "en" : "hi"}>
          {language === "en" ? result.guidanceEnglish : result.guidanceHindi}
        </p>
      </section>

      <p className="risk-disclaimer">
        This is automated risk guidance, not a certain verdict. Scores are generated by an AI model
        and can vary between runs — treat the risk band as the signal, not the exact number. Verify
        through official channels before acting.
      </p>
    </div>
  );
}
